// spec-530 t-3 — the attribution seam on the clause write path.
//
// A clause write regenerates its section's `content` (regenerateSectionContentTx),
// and `doc_sections` is an activity-bearing table [per std-32 cl-9]: it carries
// actor_user_id / actor_name / channel as first-class columns (db/schema.ts:317-319).
// `updateSection` stamps them ("re-attribute on edit — who touched it last",
// sections.ts:348). The clause path did not, so the SAME row was attributed when
// written one way and anonymous when written the other — and the clause verbs are the
// only way a Standard's rule text can be edited at all (update_section hard-rejects on
// a Standard, agent/handlers/sections.ts:228).
//
// Flagged as drift on std-32 §2 (standards/std-32/comments/c-2).

import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { eq } from "drizzle-orm";
import { db } from "../db/connection.js";
import { documents, docSections, users } from "../db/schema.js";
import { createDocDraft } from "./documents.js";
import { addSection } from "./sections.js";
import { createClause, updateClause, deleteClause } from "./clauses.js";
import { makeTestMemex } from "./test-helpers.js";
import type { RequestCtx } from "./mutate.js";
import { tagAc } from "@memex-ai-ac/vitest";

const AC_21 = "mindset-prod/memex-building-itself/specs/spec-530/acs/ac-21";

const createdDocIds: string[] = [];
const createdUserIds: string[] = [];
let memexId: string;
/** The clause EDITOR — distinct from the section's author, so a passing assertion
 *  proves re-attribution happened rather than a value left over from creation. */
let editor: { id: string; name: string };
/** The section's original author. Never edits a clause. */
let author: { id: string };

// std-37: per-worker-unique identifiers so parallel workers never collide on email.
function uniqueEmail(who: string): string {
  return `spec530-${who}-${process.env.VITEST_WORKER_ID ?? "0"}-${process.hrtime.bigint()}@example.com`;
}

async function makeUser(who: string, name: string): Promise<{ id: string; name: string }> {
  const [row] = await db
    .insert(users)
    .values({ email: uniqueEmail(who), name } as typeof users.$inferInsert)
    .returning();
  createdUserIds.push(row.id);
  return { id: row.id, name };
}

beforeAll(async () => {
  memexId = await makeTestMemex("s530attr");
  editor = await makeUser("editor", "Clause Editor");
  author = await makeUser("author", "Section Author");
});

afterAll(async () => {
  for (const id of createdDocIds) {
    await db.delete(documents).where(eq(documents.id, id));
  }
  for (const id of createdUserIds) {
    await db.delete(users).where(eq(users.id, id));
  }
});

/** ctx as an authenticated in-app agent write by the editor. */
function editorCtx(): RequestCtx {
  return { actorUserId: editor.id, channel: "in_app_agent" };
}

/** A section authored by `author` over REST, with one clause on it. Its attribution
 *  columns therefore start populated — but pointing at someone OTHER than the editor. */
async function seededSection(): Promise<{ sectionId: string; clauseId: string }> {
  const doc = await createDocDraft(memexId, "Attribution Test Standard", "purpose");
  createdDocIds.push(doc.id);
  const section = await addSection(
    memexId,
    doc.id,
    "rule",
    "",
    undefined,
    undefined,
    { actorUserId: author.id, channel: "rest_ui" },
  );
  // Seed the clause AS THE AUTHOR too. It matters: an unattributed seed would null
  // the section's actor columns (that is the whole point of the change), and the
  // re-attribution test below would then be asserting against null rather than
  // against a real prior author.
  const clause = await createClause(memexId, section.id, "The original rule.", undefined, {
    actorUserId: author.id,
    channel: "rest_ui",
  });
  return { sectionId: section.id, clauseId: clause.id };
}

async function sectionRow(sectionId: string) {
  const row = await db.query.docSections.findFirst({ where: eq(docSections.id, sectionId) });
  return row!;
}

describe("spec-530 t-3: clause writes attribute the section row they regenerate", () => {
  it("updateClause stamps actor + channel on the regenerated section (ac-21)", async () => {
    tagAc(AC_21);
    const { sectionId, clauseId } = await seededSection();

    await updateClause(memexId, clauseId, "The corrected rule.", editorCtx());

    const row = await sectionRow(sectionId);
    // The content really was regenerated by this write...
    expect(row.content).toContain("The corrected rule.");
    // ...so the row must say WHO did it and HOW [per std-32 cl-1, cl-3, cl-4].
    expect(row.actorUserId).toBe(editor.id);
    expect(row.actorName).toBe(editor.name);
    expect(row.channel).toBe("in_app_agent");
  });

  it("createClause stamps actor + channel on the regenerated section (ac-21)", async () => {
    tagAc(AC_21);
    const { sectionId } = await seededSection();

    await createClause(memexId, sectionId, "An added rule.", undefined, editorCtx());

    const row = await sectionRow(sectionId);
    expect(row.content).toContain("An added rule.");
    expect(row.actorUserId).toBe(editor.id);
    expect(row.actorName).toBe(editor.name);
    expect(row.channel).toBe("in_app_agent");
  });

  it("deleteClause stamps actor + channel on the regenerated section (ac-21)", async () => {
    tagAc(AC_21);
    const { sectionId, clauseId } = await seededSection();

    await deleteClause(memexId, clauseId, editorCtx());

    const row = await sectionRow(sectionId);
    expect(row.actorUserId).toBe(editor.id);
    expect(row.actorName).toBe(editor.name);
    expect(row.channel).toBe("in_app_agent");
  });

  it("re-attributes rather than preserving the section author (ac-21)", async () => {
    tagAc(AC_21);
    const { sectionId, clauseId } = await seededSection();
    // Precondition: the section starts attributed to someone else entirely.
    expect((await sectionRow(sectionId)).actorUserId).toBe(author.id);

    await updateClause(memexId, clauseId, "Edited by someone else.", editorCtx());

    // "Who touched it last" — the same semantics updateSection already has
    // (sections.ts:348). A clause edit is an edit of the section's text.
    expect((await sectionRow(sectionId)).actorUserId).toBe(editor.id);
  });

  it("an unattributed caller still writes — attribution degrades, never throws", async () => {
    tagAc(AC_21);
    const { sectionId, clauseId } = await seededSection();

    // No ctx at all: server-internal callers (migrations, backfills) must keep working.
    await updateClause(memexId, clauseId, "Written with no ctx.");

    const row = await sectionRow(sectionId);
    expect(row.content).toContain("Written with no ctx.");
    expect(row.actorUserId).toBeNull();
    expect(row.channel).toBeNull();
  });
});
