// spec-121 mechanism 2 — deterministic test-shape sketches appended to
// `resolve_decision`. When a decision resolves with linked implementation ACs,
// the response suggests the shape of the test that would verify each, with a
// paste-ready `tagAc(...)` call. The agent reads this with the decision still
// warm and writes the verification immediately.
//
// dec-5: the sketch is generated by a synchronous deterministic keyword matcher
// — no LLM, no network on this (high-frequency) path. The matcher's consumer is
// already an LLM (the coding agent), so a deterministic pointer plus a capable
// agent yields the test without a server-side model round-trip. LLM generation
// stays the documented v0.2 escape hatch if the generic fall-through fires too
// often in practice.

export interface SketchAc {
  seq: number;
  statement: string;
  canonicalRef: string;
}

/**
 * Map an AC statement to a suggested test shape via the deterministic
 * keyword-pattern matcher (dec-5 v0.1). The first matching pattern wins;
 * a statement matching none falls through to the generic shape (ac-18).
 */
export function sketchShapeForStatement(statement: string): string {
  const s = statement.toLowerCase();

  const statusMatch = s.match(/returns?\s+(?:a\s+)?(\d{3})/);
  if (statusMatch) {
    return `HTTP request, assert status ${statusMatch[1]}`;
  }
  if (/documents?\s+only|no\s+.*references?|absent|removed|deleted|no longer/.test(s)) {
    return "read the source, assert the absence";
  }
  if (/accepts|stores|emits|populates/.test(s)) {
    return "behavioural test against the named endpoint";
  }
  if (/field|column|payload|wire format/.test(s)) {
    return "payload-shape assertion";
  }
  return "write a test that asserts the AC's claim";
}

// One-line intro — kept inline (a single structural label, the std-15 §6
// one-liner tolerance, like COMPLETION_NUDGE).
const SKETCH_INTRO =
  "This decision's implementation ACs are pending verification. For each:";

/**
 * Build the sketch block appended to a `resolve_decision` response. Returns ""
 * when the decision has no linked implementation ACs (ac-19: no link → no
 * block — the caller falls back to the generic author-your-ACs nudge).
 */
export function buildSketchBlock(acs: SketchAc[]): string {
  if (acs.length === 0) return "";
  // Leading BLANK line ("", "" → "\n\n"), not just a newline: nudges appended
  // to a tool result start after the first blank line, the convention the doc
  // chat's first-chunk display split relies on (spec-157 dec-1).
  const lines: string[] = ["", "", SKETCH_INTRO, ""];
  for (const ac of acs) {
    lines.push(`  ac-${ac.seq} (${ac.statement})`);
    lines.push(`    suggested test shape: ${sketchShapeForStatement(ac.statement)}`);
    lines.push(`    tagAc('${ac.canonicalRef}')`);
  }
  return lines.join("\n");
}
