// b-31 W8 t-17 — generate the canonical tool-inventory markdown that the
// Anthropic Connectors Directory submission form asks for. Reads tool-specs.ts
// (30 shared specs) and adds the MCP-only inline `list_memexes` for a total
// of 31 tools. Output is written to docs/mcp-tool-inventory.md.
//
// Re-run before each directory submission so the file stays in sync with the
// code: `tsx scripts/generate-tool-inventory.ts`.

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { toolSpecs, type ToolAnnotations } from "../src/agent/tool-specs.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = resolve(__dirname, "..", "..", "..", "docs", "mcp-tool-inventory.md");

// MCP-only `list_memexes` is registered inline in mcp/tools.ts, not in the
// shared spec list. Keep these annotations in lockstep with tools.ts.
const LIST_MEMEXES_ANNOTATIONS: ToolAnnotations = {
  title: "List Memexes",
  readOnlyHint: true,
  destructiveHint: false,
};

interface InventoryEntry {
  name: string;
  description: string;
  annotations: ToolAnnotations;
}

const inventory: InventoryEntry[] = [
  {
    name: "list_memexes",
    description:
      "List the Memexes this user is a member of, grouped by namespace. " +
      "Returns `<namespace>/<memex>` identifiers other scoped tools accept as their `memex` arg.",
    annotations: LIST_MEMEXES_ANNOTATIONS,
  },
  ...toolSpecs.map((s) => ({
    name: s.name,
    // Trim long descriptions to one sentence for the inventory; full text
    // lives in the spec file.
    description: s.description.split(/(?<=\.) /)[0],
    annotations: s.annotations,
  })),
];

function classify(a: ToolAnnotations): string {
  if (a.readOnlyHint) return "read-only";
  if (a.destructiveHint) return "**destructive**";
  return "write";
}

const readOnlyCount = inventory.filter((t) => t.annotations.readOnlyHint).length;
const destructiveCount = inventory.filter((t) => t.annotations.destructiveHint).length;
const writeCount = inventory.length - readOnlyCount - destructiveCount;

const lines: string[] = [];
lines.push("# Memex MCP — tool inventory");
lines.push("");
lines.push(
  "Auto-generated by `scripts/generate-tool-inventory.ts`. Do not edit by hand — re-run " +
    "the script and commit. The Anthropic Connectors Directory submission form embeds this " +
    "verbatim.",
);
lines.push("");
lines.push(`**Total tools**: ${inventory.length}`);
lines.push(`- ${readOnlyCount} read-only`);
lines.push(`- ${destructiveCount} destructive (Claude prompts before calling)`);
lines.push(`- ${writeCount} reversible writes`);
lines.push("");
lines.push("| Tool | Title | Classification | Description |");
lines.push("|---|---|---|---|");
for (const t of inventory) {
  // Markdown table — escape pipes inside descriptions.
  const desc = t.description.replace(/\|/g, "\\|");
  lines.push(`| \`${t.name}\` | ${t.annotations.title} | ${classify(t.annotations)} | ${desc} |`);
}
lines.push("");

writeFileSync(OUT_PATH, lines.join("\n"));
console.log(`Wrote ${OUT_PATH}`);
console.log(`  ${inventory.length} tools (${readOnlyCount} R/O, ${destructiveCount} destructive, ${writeCount} write)`);
